openldapaccountdata:
    container_name: openldapaccount-data
    image: learninglayers/openldapaccount-data:0.0.6
openldapaccount:
    container_name: openldapaccount
    image: learninglayers/openldapaccount:0.0.5
    volumes_from:
        - openldapaccountdata
    links:
        - openldap
        - oidc
    environment:
        - PWM_LDAP_ADMINS=<value>koren</value><value>nicolaescu</value>
    env_file:
        - common.env
        - services/openldap/LDAP.env
    links:
        - openldap
    volumes:
        - /dev/urandom:/dev/random
